### ISSUE TITLE
Missing utilities.h from cgats.cpp

### ISSUE THREAD

**Issue by cereal-s** [doug3236/ABWProfilePatches#1]
Hello,

thank you for sharing such work, I'm trying to compile your program on a Ubuntu 18.04 machine by running:

`cgats.cpp color_conversions.cpp Create_CGATS_for_ABW.cpp Create_CGATS_for_ABW_Routines.cpp PatchFilter.cpp -o ABWProfileMaker`

But I get some errors, the first is the missing header file utilities.h from cgats.cpp, I don't see it in the repository, can you give me a hint to solve it? Thank you.

**Comment by doug3236** [comment]
Thanks. I added utilities.h and a sample ICC profile created from this program with Argyll.. Also added the batch file (windows) that shows the process to use Argyll.

**Comment by cereal-s** [comment]
Thank you this helped. I had to make some changes because Linux g++ does not handle fopen_s() which is a Microsoft function, so I added an adapter that switches to fopen().

Now I can compile it by running:

    g++ -std=gnu++1z *.cpp -o ABWProfileMaker

This issue can be considered solved. I have another few questions, but I will open a new thread.
